spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&&useSSL=false&serverTimezone=UTC
    username: root
    password: qq1271396448
    driver-class-name: com.mysql.jdbc.Driver