spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guess-song?useUnicode=true&characterEncoding=utf-8&&useSSL=false&serverTimezone=UTC
    username: root
    password: LemonLive@2021
    driver-class-name: com.mysql.jdbc.Driver